import { ItemData } from '../typings/item';

export const Items: {
  [key: string]: ItemData | undefined;
} = {
  water: {
    name: 'water',
    close: false,
    label: 'Water Bottle',
    stack: true,
    usable: true,
    count: 0,
    width: 1,
    height: 2,
  },
  burger: {
    name: 'burger',
    close: false,
    label: 'Burger',
    stack: true,
    usable: true,
    count: 0,
    width: 1,
    height: 1,
  },
  weapon_pistol: {
    name: 'weapon_pistol',
    close: false,
    label: 'Pistol',
    stack: false,
    usable: true,
    count: 0,
    width: 2,
    height: 1,
    weapon: true,
  },
  weapon_assaultrifle: {
    name: 'weapon_assaultrifle',
    close: false,
    label: 'Assault Rifle',
    stack: false,
    usable: true,
    count: 0,
    width: 5,
    height: 2,
    weapon: true,
    rarity: 'epic',
  },
  medkit: {
    name: 'medkit',
    close: false,
    label: 'Medical Kit',
    stack: false,
    usable: true,
    count: 0,
    width: 2,
    height: 2,
    rarity: 'uncommon',
  },
  radio: {
    name: 'radio',
    close: false,
    label: 'Radio',
    stack: false,
    usable: true,
    count: 0,
    width: 1,
    height: 2,
  },
  bandage: {
    name: 'bandage',
    close: false,
    label: 'Bandage',
    stack: true,
    stackSize: 20,
    usable: true,
    count: 0,
    width: 1,
    height: 1,
  },
  weapon_smg: {
    name: 'weapon_smg',
    close: false,
    label: 'SMG',
    stack: false,
    usable: true,
    count: 0,
    width: 3,
    height: 2,
    weapon: true,
  },
  armour: {
    name: 'armour',
    close: false,
    label: 'Body Armor',
    stack: false,
    usable: true,
    count: 0,
    width: 2,
    height: 3,
    rarity: 'rare',
  },
  phone: {
    name: 'phone',
    close: false,
    label: 'Phone',
    stack: false,
    usable: true,
    count: 0,
    width: 1,
    height: 1,
  },
  lockpick: {
    name: 'lockpick',
    close: false,
    label: 'Lockpick',
    stack: true,
    stackSize: 15,
    usable: true,
    count: 0,
    width: 1,
    height: 1,
  },
  ammo_9mm: {
    name: 'ammo_9mm',
    close: true,
    label: '9mm Ammo',
    stack: true,
    usable: false,
    count: 0,
    width: 1,
    height: 1,
  },
  knife: {
    name: 'knife',
    close: false,
    label: 'Knife',
    stack: false,
    usable: true,
    count: 0,
    width: 1,
    height: 2,
  },
  at_suppressor_light: {
    name: 'at_suppressor_light',
    close: false,
    label: 'Suppressor',
    stack: false,
    usable: true,
    count: 0,
    width: 1,
    height: 1,
    component: true,
    type: 'muzzle',
    compatibleWeapons: ['weapon_pistol', 'weapon_smg'],
  },
  at_suppressor_heavy: {
    name: 'at_suppressor_heavy',
    close: false,
    label: 'Tactical Suppressor',
    stack: false,
    usable: true,
    count: 0,
    width: 1,
    height: 1,
    component: true,
    type: 'muzzle',
    compatibleWeapons: ['weapon_assaultrifle', 'weapon_smg'],
  },
  at_scope_macro: {
    name: 'at_scope_macro',
    close: false,
    label: 'Macro Scope',
    stack: false,
    usable: true,
    count: 0,
    width: 1,
    height: 1,
    component: true,
    type: 'sight',
    compatibleWeapons: ['weapon_assaultrifle', 'weapon_smg'],
  },
  at_clip_extended: {
    name: 'at_clip_extended',
    close: false,
    label: 'Extended Clip',
    stack: false,
    usable: true,
    count: 0,
    width: 1,
    height: 1,
    component: true,
    type: 'magazine',
    compatibleWeapons: ['weapon_pistol', 'weapon_assaultrifle', 'weapon_smg'],
  },
  at_grip: {
    name: 'at_grip',
    close: false,
    label: 'Grip',
    stack: false,
    usable: true,
    count: 0,
    width: 1,
    height: 1,
    component: true,
    type: 'grip',
    compatibleWeapons: ['weapon_assaultrifle', 'weapon_smg'],
  },
  at_flashlight: {
    name: 'at_flashlight',
    close: false,
    label: 'Flashlight',
    stack: false,
    usable: true,
    count: 0,
    width: 1,
    height: 1,
    component: true,
    type: 'flashlight',
    compatibleWeapons: ['weapon_pistol', 'weapon_assaultrifle', 'weapon_smg'],
  },
};
