import { ItemData } from '../typings/item';

export const Items: {
  [key: string]: ItemData | undefined;
} = {
  lockpick: {
    name: 'lockpick',
    close: false,
    label: 'Lockpick',
    stack: true,
    usable: true,
    count: 0,
    description: 'Simple lockpick that breaks easily and can pick basic door locks',
  },
  phone: {
    name: 'phone',
    close: false,
    label: 'Handphone',
    stack: true,
    usable: true,
    count: 0,
  },
  stone: {
    name: 'stone',
    close: false,
    label: 'Batu',
    stack: true,
    usable: true,
    count: 0,
    description: 'Stone to make something',
  },
  weapon_pistol: {
    name: 'weapon_pistol',
    close: false,
    label: 'Pistol',
    stack: false,
    usable: false,
    count: 0,
    description: 'Strong firearms that could finish someone life',
  },
  water_bottle: {
    name: 'water_bottle',
    close: false,
    label: 'Water Bottle',
    stack: true,
    usable: true,
    count: 0,
    description: 'A piece of water of bottle',
  },
  tosti: {
    name: 'tosti',
    close: false,
    label: 'Tosti',
    stack: true,
    usable: true,
    count: 0,
    description: 'A piece of bread',
  },
  money: {
    name: 'money',
    close: false,
    label: 'Money',
    stack: true,
    usable: true,
    count: 0,
    description: 'A valuable things',
  },
  black_money: {
    name: 'black_money',
    close: false,
    label: 'Dirty Money',
    stack: true,
    usable: true,
    count: 0,
    description: 'A valuable things',
  },
};
